// generated by gen-options; DO NOT EDIT

package example

import "go/ast"

// MyOptionFirst the generated function is MyOptionFirst
func MyOptionFirst(fst int) func(*Foo) {
	return func(f *Foo) {
		f.fst = fst
	}
}

// MyOptionSecond the generated function is MyOptionSecond
func MyOptionSecond(snd *Bar) func(*Foo) {
	return func(f *Foo) {
		f.snd = snd
	}
}

// MyOptionTrd the generated function is MyOptionTrd
func MyOptionTrd(trd []string) func(*Foo) {
	return func(f *Foo) {
		f.trd = trd
	}
}

// MyOptionFourth the generated function is MyOptionFourth
// fourth field first comment 2nd line
func MyOptionFourth(fourth *ast.Field) func(*Foo) {
	return func(f *Foo) {
		f.fourth = fourth
	}
}
