// generated by gen-options; DO NOT EDIT

package example

import "go/ast"

type Option func(*Foo)

// MyOptionFirst the generated function is MyOptionFirst
func MyOptionFirst(fst int) Option {
	return func(f *Foo) {
		f.fst = fst
	}
}

func MyOptionSecond(snd *Bar) Option {
	return func(f *Foo) {
		f.snd = snd
	}
}

// MyOptionTrd the generated function is MyOptionTrd
func MyOptionTrd(trd []string) Option {
	return func(f *Foo) {
		f.trd = trd
	}
}

// MyOptionFourth the generated function is MyOptionFourth
// fourth field first comment 2nd line
func MyOptionFourth(fourth *ast.Field) Option {
	return func(f *Foo) {
		f.fourth = fourth
	}
}
